# COMMON #
ENVIRONMENT: DEV
SPOTIFY_CLIENTID: <AddRegisteredSpotifyClientID>
SPOTIFY_SECRET: <AddRegisteredSpotifySecret>
ALGOLIA_APP_ID: <AddRegisteredAlgoliaAppID>
ALGOLIA_SECRET_ID: <AddRegisteredAlgoliaSecretID>

# DEV #
HOSTNAME_DEV: http://localhost:8080
FIREBASE_PROJECTID_DEV: <AddRegisteredFirebaseProjectID>
ALGOLIA_INDEX_NAME_DEV: <AddCreatedAlgoliaIndexName>
APPLE_AUTH_TEMPLATE_PATH_DEV: cmd/appleauth/templates
APPLE_PRIVATE_KEY_PATH_DEV: cmd/createappledevtoken/apple_private_key.p8
